//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkEFI.Crosscutting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ParkEFI.Crosscutting.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usar el correo como usuario?.
        /// </summary>
        public static string Authentication_Display_IsEmailTheUsername {
            get {
                return ResourceManager.GetString("Authentication_Display_IsEmailTheUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las contraseñas no coinciden..
        /// </summary>
        public static string Authentication_Validation_PasswordCompare {
            get {
                return ResourceManager.GetString("Authentication_Validation_PasswordCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de nacimiento.
        /// </summary>
        public static string Common_BirthDate {
            get {
                return ResourceManager.GetString("Common_BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar contraseña.
        /// </summary>
        public static string Common_ConfirmPassword {
            get {
                return ResourceManager.GetString("Common_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo eletronico.
        /// </summary>
        public static string Common_Email {
            get {
                return ResourceManager.GetString("Common_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellidos.
        /// </summary>
        public static string Common_FamilyName {
            get {
                return ResourceManager.GetString("Common_FamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genero.
        /// </summary>
        public static string Common_Gender {
            get {
                return ResourceManager.GetString("Common_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombres.
        /// </summary>
        public static string Common_GivenName {
            get {
                return ResourceManager.GetString("Common_GivenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cedula de identidad.
        /// </summary>
        public static string Common_IdentityCedula {
            get {
                return ResourceManager.GetString("Common_IdentityCedula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string Common_Password {
            get {
                return ResourceManager.GetString("Common_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string Common_PersonStatus {
            get {
                return ResourceManager.GetString("Common_PersonStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo persona.
        /// </summary>
        public static string Common_PersonType {
            get {
                return ResourceManager.GetString("Common_PersonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono movil.
        /// </summary>
        public static string Common_PhoneNumber {
            get {
                return ResourceManager.GetString("Common_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo &apos;{0}&apos; no puede tener más de {1} caracteres..
        /// </summary>
        public static string Common_Validation_FieldMaxLength {
            get {
                return ResourceManager.GetString("Common_Validation_FieldMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo &apos;{0}&apos; es requerido..
        /// </summary>
        public static string Common_Validation_FieldRequired {
            get {
                return ResourceManager.GetString("Common_Validation_FieldRequired", resourceCulture);
            }
        }
    }
}
